services:
  postgres:
    image: postgres:latest
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./src/scripts/sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=plspay
    command:
      - 'postgres'
      - '-c'
      - 'wal_level=logical'
    restart: always